### ISSUE TITLE
Wrong contribution value for Acala crowdloan

### ISSUE THREAD

**Issue by Dauta** [TalismanSociety/talisman-web#168]
Hi 👋

First of all, thank you so much for working on Talisman. It's such a nice UX, blows everything else I've used out of the water. 
I understand the project is quite new and some issues are expected. 
To sum up, the portfolio page shows my contribution to the Acala crowndloan to be double of what it's supposed to be (shows 100 DOT instead of 50). 
I double-checked the contribution on https://acala.network/acala/join-acala.
Would be happy to give a hand in tracking down the bug, if you're looking for contributions.

**Comment by alecdwm** [comment]
Hey @Dauta thanks for the bug report!

We tracked down the issue - the value we were using from Acala's API, `contributionAmount`, was the total of *all* contributions both lcDOT and direct.

What we should be using is `proxyAmount` - the total of just lcDOT contributions. We already have the direct contributions indexed from the chain itself.

Should be fixed by https://github.com/TalismanSociety/talisman-web/commit/b8afae37f044eabcb5791dcdccfbebdb01ca5610, which is now live at https://app.talisman.xyz

Would you mind giving it a test and confirming that your acala contribution now shows the correct amount?

**Comment by Dauta** [comment]
@alecdwm, 
Thanks so much for looking into it and for the clear explanation of what was going wrong. 
I can confirm that the dashboard now shows the correct contribution amount!
